############################################################
# +------------------------------------------------------+ #
# |             TokenShop Config File                    | #
# +------------------------------------------------------+ #
############################################################

# Configuration file for TokenSho
# Plugin developed by millenium200

tokens:
